export const methods = ['GET', 'POST', 'PUT', 'DELETE'];
export const example = {
  rest: '/POST/aHR0cHM6Ly9qc29ucGxhY2Vob2xkZXIudHlwaWNvZGUuY29tL3Bvc3Rz/eyJtZXRob2QiOiJQT1NUIiwiaGVhZGVycyI6eyJ0aXRsZSI6ImVhIG1vbGVzdGlhcyBxdWFzaSBleGVyY2l0YXRpb25lbSByZXBlbGxhdCBxdWkgaXBzYSBzaXQgYXV0IiwiYm9keSI6IntcbiAgXCJ0aXRsZVwiOiBcInt7dGl0bGV9fVwiLFxuICBcImJvZHlcIjogXCJ7e2JvZHl9fVwiXG59IiwiY29udGVudFR5cGUiOiJhcHBsaWNhdGlvbi9qc29uIn19?Content-Type=application/json',
  graph:
    '/GRAPHQL/eyJ1cmxCYXNlIjoiaHR0cHM6Ly9yaWNrYW5kbW9ydHlhcGkuY29tL2dyYXBocWwiLCJ1cmxTREwiOiJodHRwczovL3JpY2thbmRtb3J0eWFwaS5jb20vZ3JhcGhxbD9zZGwifQ__/eyJxdWVyeSI6IiBxdWVyeSAoJHBhZ2U6XG5JbnQpICB7XG4gIGNoYXJhY3RlcnMocGFnZTpcbiAgJHBhZ2UpICB7XG4gICAgaW5mbyB7XG4gICAgICBjb3VudCBcbiAgICB9IFxuICB9IFxufSIsInZhcmlhYmxlcyI6IntcbiAgXCJwYWdlXCI6IDJcbn0ifQ__',
};
